-- =====================
-- DROP TABLES IF EXISTS
-- =====================
DROP TABLE IF EXISTS student_attendance CASCADE;
DROP TABLE IF EXISTS loan CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS book CASCADE;
DROP TABLE IF EXISTS schedule CASCADE;
DROP TABLE IF EXISTS instructor CASCADE;
DROP TABLE IF EXISTS classroom CASCADE;
DROP TABLE IF EXISTS class CASCADE;
DROP TABLE IF EXISTS student_faculty CASCADE;
DROP TABLE IF EXISTS student_group CASCADE;
DROP TABLE IF EXISTS tuition CASCADE;
DROP TABLE IF EXISTS specialization CASCADE;
DROP TABLE IF EXISTS faculty CASCADE;
DROP TABLE IF EXISTS student_details CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- =====================
-- USERS
-- =====================
CREATE TABLE users (
                       user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       login VARCHAR(16) NOT NULL UNIQUE,
                       password VARCHAR(25) NOT NULL,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       is_active BOOLEAN NOT NULL,
                       user_role VARCHAR(10) NOT NULL,
                       created DATE NOT NULL,
                       updated DATE
);

-- =====================
-- STUDENT DETAILS
-- =====================
CREATE TABLE student_details (
                                 student_detail_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 first_name VARCHAR(50) NOT NULL,
                                 last_name VARCHAR(50) NOT NULL,
                                 gender VARCHAR(20) NOT NULL,
                                 phone_number CHAR(9) NOT NULL UNIQUE,
                                 album_number CHAR(5) NOT NULL UNIQUE,
                                 user_id INT UNIQUE,
                                 FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- =====================
-- FACULTY
-- =====================
CREATE TABLE faculty (
                         faculty_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL UNIQUE
);

-- =====================
-- SPECIALIZATION
-- =====================
CREATE TABLE specialization (
                                specialization_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name VARCHAR(255) NOT NULL UNIQUE,
                                faculty_id INT,
                                FOREIGN KEY (faculty_id) REFERENCES faculty(faculty_id)
);

-- =====================
-- TUITION
-- =====================
CREATE TABLE tuition (
                         tuition_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         is_active BOOLEAN NOT NULL
);

-- =====================
-- STUDENT GROUP
-- =====================
CREATE TABLE student_group (
                               group_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name VARCHAR(20) NOT NULL,
                               semester INT NOT NULL
);

-- =====================
-- STUDENT-FACULTY
-- =====================
CREATE TABLE student_faculty (
                                 student_faculty_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 student_detail_id INT NOT NULL,
                                 faculty_id INT NOT NULL,
                                 semester INT NOT NULL,
                                 tuition_id INT,
                                 group_id INT,
                                 FOREIGN KEY (student_detail_id) REFERENCES student_details(student_detail_id),
                                 FOREIGN KEY (faculty_id) REFERENCES faculty(faculty_id),
                                 FOREIGN KEY (tuition_id) REFERENCES tuition(tuition_id),
                                 FOREIGN KEY (group_id) REFERENCES student_group(group_id)
);

-- =====================
-- CLASS
-- =====================
CREATE TABLE class (
                       class_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       subject_name VARCHAR(30) NOT NULL,
                       start_hour TIME NOT NULL,
                       end_hour TIME NOT NULL,
                       group_id INT,
                       FOREIGN KEY (group_id) REFERENCES student_group(group_id)
);

-- =====================
-- CLASSROOM
-- =====================
CREATE TABLE classroom (
                           classroom_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           building VARCHAR(10) NOT NULL,
                           number VARCHAR(10) NOT NULL
);

-- =====================
-- INSTRUCTOR
-- =====================
CREATE TABLE instructor (
                            instructor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            first_name VARCHAR(50) NOT NULL,
                            last_name VARCHAR(50) NOT NULL,
                            email VARCHAR(100) NOT NULL,
                            department VARCHAR(50) NOT NULL
);

-- =====================
-- SCHEDULE
-- =====================
CREATE TABLE schedule (
                          schedule_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          class_id INT NOT NULL,
                          instructor_id INT NOT NULL,
                          classroom_id INT NOT NULL,
                          start_date DATE NOT NULL,
                          end_date DATE NOT NULL,
                          week_day INT NOT NULL,
                          class_type VARCHAR(20),
                          FOREIGN KEY (class_id) REFERENCES class(class_id),
                          FOREIGN KEY (instructor_id) REFERENCES instructor(instructor_id),
                          FOREIGN KEY (classroom_id) REFERENCES classroom(classroom_id)
);

-- =====================
-- ATTENDANCE
-- =====================
CREATE TABLE student_attendance (
                                    attendance_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    user_id INT NOT NULL,
                                    schedule_id INT NOT NULL,
                                    attendance_date DATE NOT NULL,
                                    status VARCHAR(20) NOT NULL,
                                    notes VARCHAR(255),
                                    FOREIGN KEY (user_id) REFERENCES users(user_id),
                                    FOREIGN KEY (schedule_id) REFERENCES schedule(schedule_id)
);

-- =====================
-- BOOK
-- =====================
CREATE TABLE book (
                      book_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      book_title VARCHAR(200) NOT NULL,
                      author VARCHAR(100) NOT NULL,
                      isbn VARCHAR(20)
);

-- =====================
-- LOAN
-- =====================
CREATE TABLE loan (
                      loan_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      loan_date DATE NOT NULL,
                      return_date DATE,
                      status VARCHAR(20) NOT NULL,
                      user_id INT,
                      book_id INT,
                      FOREIGN KEY (user_id) REFERENCES users(user_id),
                      FOREIGN KEY (book_id) REFERENCES book(book_id)
);

-- =====================
-- PAYMENTS
-- =====================
CREATE TABLE payments (
                          payment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          term TIMESTAMP NOT NULL,
                          amount DECIMAL(10,2) NOT NULL,
                          payment_date DATE,
                          payment_amount DECIMAL(10,2),
                          status VARCHAR(20) NOT NULL,
                          tuition_id INT,
                          FOREIGN KEY (tuition_id) REFERENCES tuition(tuition_id)
);
